# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-JSONRPC
version:      0.05
version_from: lib/CGI/JSONRPC.pm
installdirs:  site
requires:
    Apache::Test:                  0
    CGI:                           3.11
    JSON::Syck:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
